# Generated by Django 2.2.17 on 2022-01-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_committee_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
