# Generated by Django 4.2.14 on 2025-09-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('committee', '0007_remove_committee_chair_remove_committee_chair_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='chairman_permissions',
            field=models.ManyToManyField(blank=True, related_name='chairman_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='other_permissions',
            field=models.ManyToManyField(blank=True, related_name='other_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='treasurer_permissions',
            field=models.ManyToManyField(blank=True, related_name='treasurer_permissions', to='auth.permission'),
        ),
    ]
