# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-24 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('infomail', '0002_auto_20181224_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomailindexpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='infomailindexpage',
            name='infopage_ptr',
        ),
        migrations.AddField(
            model_name='infomailindexpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
