# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('infomail', '0003_auto_20181224_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomailarticlepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='infomailarticlepage',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infomailarticlepage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infomailarticlepage',
            name='link_text',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomailpage',
            name='intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='infomailpage',
            name='intro_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infomailpage',
            name='intro_image_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='infomailarticlepage',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
