# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-25 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infomail', '0004_auto_20181224_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomailarticlepage',
            name='link_text',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='infomailpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Intro is an optional full-width container shown on top of the email under the logo.'),
        ),
        migrations.AlterField(
            model_name='infomailpage',
            name='intro_image_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The image text is shown underneath the intro image and describes the image.'),
        ),
    ]
