# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-26 11:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infomail', '0005_auto_20181226_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomailindexpage',
            name='description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
