# Generated by Django 2.2.2 on 2019-07-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190712_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
