# Generated by Django 2.2.2 on 2019-10-11 11:56

from django.db import migrations, models
from account.models import Profile


def fix_liu_id():
    for profile in Profile.objects.all():
        try:
            int(profile.liu_card_id)
        except:
            profile.liu_card_id = "0"

        profile.save()


def fix_zero():
    for profile in Profile.objects.all():
        if profile.liu_card_id == 0:
            profile.liu_card_id = None
            profile.save()


class Migration(migrations.Migration):

    dependencies = [("account", "0006_profile_infomail_subscriber")]

    operations = [
        migrations.RunPython(fix_liu_id),
        migrations.AlterField(
            model_name="profile",
            name="liu_card_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(fix_zero),
    ]
