# Generated by Django 2.2.2 on 2019-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_infomail_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liu_card_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
