# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20180226_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('until_further_notice', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
