# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20180326_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='out_date',
        ),
    ]
