# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_object_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageroom',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
