# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20180409_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='can_borrow_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='object',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
