# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20180417_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='can_borrow_from',
        ),
        migrations.AddField(
            model_name='object',
            name='can_be_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
