# Generated by Django 2.2.17 on 2021-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0008_auto_20211119_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetentry',
            old_name='banknr',
            new_name='bankNr',
        ),
        migrations.RenameField(
            model_name='budgetentry',
            old_name='clearing',
            new_name='clearingNr',
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='bankName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='committee',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
