# Generated by Django 2.2.17 on 2022-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0011_auto_20220120_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
