# Generated by Django 2.2.17 on 2022-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0016_budgetentry_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='image2',
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='image2',
            field=models.ManyToManyField(blank=True, null=True, related_name='model', to='budgetportal.Image'),
        ),
    ]
