# Generated by Django 2.2.17 on 2022-02-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0021_auto_20220203_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='list_test',
        ),
    ]
