# Generated by Django 2.2.17 on 2022-02-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0023_file_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='image2',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
