# Generated by Django 2.2.17 on 2022-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0024_auto_20220210_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
