# Generated by Django 2.2.17 on 2022-03-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0026_remove_budgetentry_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='budgetportal.BudgetEntry'),
        ),
    ]
