services:
  backend:
    container_name: D-Sektionen-Backend
    image: registry.d-sektionen.se/backend:latest
    restart: unless-stopped
    command: uwsgi --ini /etc/uwsgi/backend.uwsgi.ini
    volumes:
      # Set the paths when deploying to production.
      - ${BACKEND_BASEDIR}/static:/code/backend/static
      - ${BACKEND_BASEDIR}/media:/code/backend/media
      - ${BACKEND_BASEDIR}/log:/var/log/
      - ${BACKEND_BASEDIR}/.YALE_ACCESS_TOKEN_CACHE:/code/.YALE_ACCESS_TOKEN_CACHE
    ports:
      # Update for production environment
      - 13337:8000
    environment:
      # Set these when deploying to production
      POSTGRES_NAME: backend
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: XXXX
      POSTGRES_HOST: 172.17.0.1
      POSTGRES_PORT: 5432
    env_file:
      # Environment variables set in portainer gui.
      - stack.env
    networks:
      - default

  home_assistant:
    container_name: D-sektionen-HA
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BACKEND_BASEDIR}/HA-config:/config
    ports:
      - 8123:8123
    networks:
      - default
      - backend-homeassistant

networks:
  default:
    driver: bridge
    name: backend_network
  backend-homeassistant:
    internal: true
