version: "3.12"

services:
  backend:
    image: registry.d-sektionen.se/backend:prod # Specify backend image
    restart: always
    command: uwsgi --ini /srv/backend.uwsgi.ini
    volumes:
      # Set the paths when deploying to production.
      #- [ini file path]:/srv/backend.uwsgi.ini
      #- [static files path]:/code/static
    ports:
      # Update for production environment
      - 127.0.0.1:XXXX:8000
    environment:
      # Set these when deploying to production
      POSTGRES_NAME: XXXX
      POSTGRES_USER: XXXX
      POSTGRES_PASSWORD: XXXX
      POSTGRES_HOST: XXXX
      POSTGRES_PORT: XXXX
    env_file:
      # Environment variable file for keys and secrets for azure authentication.
      - XXXX/.env
    networks:
      - default # network outside

networks:
  default:
    name: backend_network
