FROM python:3.12-alpine AS base
WORKDIR /app
RUN apk add gcc musl-dev

FROM base AS installer
ENV DJANGO_SETTINGS_MODULE=backend.app.settings_development
COPY requirements.*txt ./
RUN pip install --no-cache-dir -r requirements.development.txt
COPY ./backend ./backend
COPY ./manage.py .
RUN mkdir ./static ./media
RUN python3 manage.py collectstatic --noinput

FROM base AS runner
COPY --from=installer /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=installer /usr/local/bin /usr/local/bin
COPY --from=installer /app/backend /app/backend
COPY --from=installer /app/manage.py .
COPY --from=installer /app/static /app/static
COPY --from=installer /app/media /app/media

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=backend.app.settings_development

ENTRYPOINT ["uvicorn", "backend.app.asgi:application", "--host", "0.0.0.0", "--port", "8000", "--reload"]
