# Generated by Django 2.2.28 on 2024-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20190228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('NL', 'Netlight'), ('CF', 'CF'), ('UN', 'Uncategorized')], default='UN', max_length=2),
        ),
    ]
