# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liu_id', models.CharField(max_length=8)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('membership_type', models.CharField(choices=[('S', 'Student Member'), ('A', 'Alumni Member'), ('H', 'Honorary Member'), ('O', 'Other')], default='S', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member')),
            ],
        ),
    ]
