# Generated by Django 2.2.17 on 2020-11-27 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20201127_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='restricted_timeslot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.ItemCategory'),
        ),
    ]
