# Generated by Django 4.2.14 on 2025-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_item_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
