# Generated by Django 4.2.14 on 2025-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
