# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='liu_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
