# Generated by Django 2.2.2 on 2019-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20181231_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=256)),
                ('program', models.CharField(blank=True, choices=[('D', 'Datateknik'), ('U', 'Mjukvaruteknik'), ('IT', 'Informationsteknologi'), ('IP', 'Innovativ Programering'), ('CS', 'Computer Science')], max_length=2)),
            ],
        ),
    ]
