# Generated by Django 2.2.2 on 2019-08-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='starting_year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
