# Generated by Django 4.2.14 on 2025-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_request_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='program',
            field=models.CharField(blank=True, choices=[('D', 'Datateknik'), ('U', 'Mjukvaruteknik'), ('IT', 'Informationsteknologi'), ('IP', 'Innovativ Programering'), ('CS', 'Computer Science'), ('CY', 'Cyber Security')], max_length=2),
        ),
    ]
