# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-13 14:44
from __future__ import unicode_literals

import cms.snippets.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('markdown', wagtailmarkdown.blocks.MarkdownBlock()), ('social', wagtail.snippets.blocks.SnippetChooserBlock(cms.snippets.models.Committee)), ('contact', wagtail.snippets.blocks.SnippetChooserBlock(cms.snippets.models.Contact)), ('page', wagtail.core.blocks.PageChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
