# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-24 14:18
from __future__ import unicode_literals

import cms.snippets.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.core.fields.StreamField([('markdown', wagtailmarkdown.blocks.MarkdownBlock()), ('richtext', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'staben', 'ol', 'ul', 'link'])), ('social', wagtail.snippets.blocks.SnippetChooserBlock(cms.snippets.models.Committee)), ('contact', wagtail.snippets.blocks.SnippetChooserBlock(cms.snippets.models.Contact)), ('page', wagtail.core.blocks.PageChooserBlock())]),
        ),
    ]
