# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-29 16:19
from __future__ import unicode_literals

import cms.snippets.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0002_auto_20181224_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'staben', 'ol', 'ul', 'link'])), ('social', wagtail.snippets.blocks.SnippetChooserBlock(cms.snippets.models.Committee)), ('contact', wagtail.snippets.blocks.SnippetChooserBlock(cms.snippets.models.Contact)), ('page', wagtail.core.blocks.PageChooserBlock())]),
        ),
    ]
