# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('infopage', '0003_auto_20181229_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
