# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_theme'),
        ('infopage', '0004_infopage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.Theme'),
        ),
    ]
