# Generated by Django 2.2.17 on 2022-02-24 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_auto_20220128_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
