# Generated by Django 2.2.17 on 2022-11-03 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committee', '0005_auto_20220421_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='chair_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
