# Generated by Django 2.2.2 on 2020-01-27 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('eventbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.EventBase')),
                ('members_only', models.BooleanField(default=False)),
                ('attendant_limit', models.IntegerField(default=0, help_text='For no limit the value should be 0.')),
                ('whitelist', models.TextField(blank=True, help_text='Separate using space, line-break or comma. Leave empty for no whitelist.')),
                ('blacklist', models.TextField(blank=True, help_text='Separate using space, line-break or comma.')),
                ('attendants', models.ManyToManyField(blank=True, related_name='_occurrence_attendants_+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('checkin.eventbase',),
        ),
    ]
