# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='admin_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_admin_group', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='section',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_user_group', to='auth.Group'),
        ),
    ]
