# Generated by Django 2.2.2 on 2019-07-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='admin_group',
        ),
        migrations.RemoveField(
            model_name='section',
            name='user_group',
        ),
    ]
