# Generated by Django 2.2.2 on 2019-10-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191011_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liu_card_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
