# Generated by Django 2.2.17 on 2023-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_calendarsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liu_card_id',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
    ]
