# Generated by Django 4.2.14 on 2024-07-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230925_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsubscription',
            name='include_events_attending',
        ),
        migrations.RemoveField(
            model_name='calendarsubscription',
            name='include_events_not_attending',
        ),
    ]
