# Generated by Django 4.2.14 on 2025-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_item_enabled'),
        ('account', '0012_rename_include_bookings_calendarsubscription_include_bookings_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsubscription',
            name='include_bookable_items',
            field=models.ManyToManyField(blank=True, default=None, to='booking.item'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='infomail_subscriber',
            field=models.BooleanField(default=True),
        ),
    ]
