# Generated by Django 2.2.2 on 2020-04-13 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0004_auto_20200411_1144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speakerrequest',
            unique_together={('user', 'meeting', 'prioritized')},
        ),
    ]
