# Generated by Django 2.2.17 on 2021-02-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20200413_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='has_voting_rights',
            field=models.BooleanField(default=True),
        ),
    ]
