# Generated by Django 2.2.17 on 2021-03-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_attendant_has_voting_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='number_of_selectable_alternatives',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
