# Generated by Django 2.2.17 on 2021-03-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_vote_number_of_selectable_alternatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='number_of_selectable_alternatives',
        ),
        migrations.AddField(
            model_name='vote',
            name='max_number_of_selectable_alternatives',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vote',
            name='min_number_of_selectable_alternatives',
            field=models.IntegerField(default=1),
        ),
    ]
