# Generated by Django 2.2.17 on 2021-04-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_vote_attendants_voted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={'ordering': ('id',)},
        ),
    ]
