# Generated by Django 2.2.28 on 2024-05-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20210925_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='current_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voting.Vote'),
        ),
    ]
