# Generated by Django 2.2.2 on 2019-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='infomail_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
