# Generated by Django 2.2.2 on 2019-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0006_profile_infomail_subscriber")]

    operations = [
        # INFO: Used to contain a profile migration changing liu_card_id to a integer field.
        # That migration causes issues when adding fields to profile.
        # Since we switched back to a string field there's no point keeping it.
    ]
