# Generated by Django 4.2.14 on 2024-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_item_enabled'),
        ('account', '0011_remove_calendarsubscription_include_events_attending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarsubscription',
            old_name='include_bookings',
            new_name='include_bookings_by_user',
        ),
        migrations.AddField(
            model_name='calendarsubscription',
            name='include_bookable_items',
            field=models.ManyToManyField(to='booking.item'),
        ),
    ]
