# Generated by Django 4.2.14 on 2025-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_calendarsubscription_include_bookable_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='infomail_sender',
            field=models.BooleanField(default=True),
        ),
    ]
