# Generated by Django 4.2.14 on 2025-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_calendarsubscription_include_bookable_items_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS public.account_profile_liu_card_id_idx;"),
        migrations.AlterField(
            model_name='profile',
            name='liu_card_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=17, null=True),
        ),
    ]
