# Generated by Django 4.2.14 on 2026-02-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_liu_card_id'),
        ('account', '0014_profile_infomail_sender'),
    ]

    operations = [
    ]
