# Generated by Django 4.2.14 on 2026-03-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_profile_phone_number'),
        ('account', '0015_merge_20260209_0915'),
    ]

    operations = [
    ]
