# Generated by Django 2.2.2 on 2020-05-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carlogging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_km', models.IntegerField(null=True)),
                ('end_km', models.IntegerField(null=True)),
                ('car_days', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('trailer', models.BooleanField(default=False)),
                ('trailer_days', models.IntegerField(null=True)),
                ('active_member', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Logg',
        ),
    ]
