# Generated by Django 2.2.2 on 2020-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0002_auto_20200502_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
