# Generated by Django 2.2.2 on 2020-09-23 13:44

from django.db import migrations, models
from backend.keylog.models import is_color_validator


class Migration(migrations.Migration):

    dependencies = [
        ('keylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='color',
            field=models.CharField(max_length=64, validators=[is_color_validator]),
        ),
    ]
