# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20171114_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='current_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.Vote'),
        ),
        migrations.AlterField(
            model_name='section',
            name='admin_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='section',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
    ]
