# Generated by Django 2.2.2 on 2020-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_speakerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='enable_speaker_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='open_attendance',
            field=models.BooleanField(default=False, help_text='Allows users to set their own attendance.'),
        ),
    ]
