# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0003_auto_20171114_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendant',
            unique_together=set([('user', 'meeting')]),
        ),
        migrations.AlterUniqueTogether(
            name='scanner',
            unique_together=set([('user', 'meeting')]),
        ),
    ]
