# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20171121_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='admin_group',
        ),
        migrations.RemoveField(
            model_name='section',
            name='user_group',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Section'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
