# Generated by Django 2.2.2 on 2019-07-12 11:37

from django.db import migrations, models
import django.db.models.deletion

# def switch_to_event(apps, schema_editor):
#     """ From non inehirtance to event inheritance """
#     OldMeeting = apps.get_model('voting', 'OldMeeting')
#     NewMeeting = apps.get_model('voting', 'NewMeeting')
#     for meeting in OldMeeting.objects.all():
#         new_event_meeting = NewMeeting.objects.create(title=meeting.title, archived=meeting.archived, current_vote=meeting.current_vote)
#         meeting.delete()

# def switch_to_noevent(apps, schema_editor):
#     """ Rollback """
#     OldMeeting = apps.get_model('voting', 'OldMeeting')
#     NewMeeting = apps.get_model('voting', 'NewMeeting')

#     for meeting in NewMeeting.objects.all():
#         new_meeting = OldMeeting.objects.create(title=meeting.title, archived=meeting.archived, current_vote=meeting.current_vote)
#         meeting.delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('checkin', '0001_initial'),
        ('voting', '0005_auto_20180207_1939'),
    ]

    # Custom made operations
    # https://oktomus.com/blog/migrate-models-when-adding-inheritance-django
    # nvm, just delete old meetings, who cares about them

    operations = [
        # migrations.RenameModel('Meeting', 'OldMeeting'),
        # migrations.CreateModel(
        #     name='NewMeeting',
        #     fields=[
        #         ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.Event')),
        #         ('current_vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.Vote')),
        #     ],
        #     bases=('checkin.event',),
        # ),
        # migrations.RunPython(switch_to_event, switch_to_noevent),
        # migrations.DeleteModel('OldMeeting'),
        # migrations.RenameModel('NewMeeting', 'Meeting'),
        migrations.DeleteModel(name='Meeting'),
        migrations.DeleteModel(name='Attendant'),
        migrations.DeleteModel(name='Vote'),
        migrations.DeleteModel(name='Alternative'),
        migrations.DeleteModel(name='MadeVote'),
        migrations.DeleteModel(name='Scanner',),
    ]

    # Generated operations

    # operations = [
    #     migrations.RemoveField(
    #         model_name='meeting',
    #         name='archived',
    #     ),
    #     migrations.RemoveField(
    #         model_name='meeting',
    #         name='id',
    #     ),
    #     migrations.RemoveField(
    #         model_name='meeting',
    #         name='name',
    #     ),
    #     migrations.RemoveField(
    #         model_name='meeting',
    #         name='section',
    #     ),
    #     migrations.AddField(
    #         model_name='meeting',
    #         name='event_ptr',
    #         field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.Event'),
    #         preserve_default=False,
    #     ),
    #     migrations.DeleteModel(
    #         name='Scanner',
    #     ),
    # ]
