# Generated by Django 2.2.17 on 2021-09-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20210409_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='attendants_voted',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='max_number_of_selectable_alternatives',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='min_number_of_selectable_alternatives',
        ),
    ]
