# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-29 15:15
from __future__ import unicode_literals

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(validators=[booking.validators.validate_datetime_within_year]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(validators=[booking.validators.validate_datetime_future]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
