# Generated by Django 2.2.2 on 2019-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190129_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='terms',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
