# Generated by Django 2.2.2 on 2019-09-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_item_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='terms',
            field=models.FileField(blank=True, null=True, upload_to='booking_terms'),
        ),
    ]
