# Generated by Django 2.2.2 on 2020-02-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200206_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisted',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
