# Generated by Django 2.2.17 on 2024-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201127_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
