# Generated by Django 2.2.2 on 2020-04-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20200407_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='speakerrequest',
            name='prioritized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='voting.Meeting'),
        ),
    ]
