# Generated by Django 2.2.17 on 2021-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20210316_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='attendants_voted',
            field=models.IntegerField(default=0),
        ),
    ]
