"""
Django settings for dsek project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    # ---
    # Project apps
    # ---
    'account',
    'storage',
    'voting.apps.VotingConfig',
    'tools',
    'membership',

    # ---
    # Django related
    # ---
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cas',
    'kronos',
    'rest_framework',
    'corsheaders',
    'channels',
    'graphene_django',

    # ---
    # Wagtail related
    # ---

    # Wagtail project apps
    'cms.misc',
    'cms.home',
    'cms.infomail',
    'cms.infopage',
    'cms.snippets',
    'cms.post',

    # Wagtail modules

    'wagtail.contrib.styleguide',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.api.v2',

    'wagtailmarkdown',
    'modelcluster',
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cas.middleware.CASMiddleware',

    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'cas.backends.CASBackend',
)

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

# used by cms for uploads
# TODO: change to a better solution in production
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

# CAS (system for LiU authentication)
CAS_SERVER_URL = "https://login.liu.se/cas/"
CAS_LOGOUT_COMPLETELY = True
CAS_PROVIDE_URL_TO_LOGOUT = True
CAS_RESPONSE_CALLBACKS = (
    'account.user.cas_callback',
)

# User roles, these users are always admins.
SYSTEM_ADMINS = [
    'patsl736',
    'samjo788',
    'anglo547',
    'jeswr740',
    'ludfo119',
    'fremo917',
    'emini757',
]

# User configuration sheet (for getting user info from a google docs sheet)
# TODO: this is outdated, look into this and remove.
SA_CREDENTIALS_FILE = 'credentials.json'
SA_FILE_ID = '1vgN5ds5LMUZ0V3lG_sHcjxCRD3NmaOTc6uVamSOxEOQ'
SA_COL_NAME = 'Namn'
SA_COL_LIU_ID = 'Liu-Id'
SA_COL_UTSKOTT = 'Utskott'
SA_COL_TITLE = 'Post utskott'

# Django REST Framework
REST_FRAMEWORK = {
    # Sets default permission requirements (403 errors) for every endpoint. Override in viewset, as shown in cms.api
    'DEFAULT_PERMISSION_CLASSES': (
        'app.permissions.AllowOptionsAuthentication',
    ),
    # Sets default authentication requirements (401 errors) for every endpoint. Override in viewset, as shown in cms.api
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# GraphQL configuration, right now only used in CMS.
GRAPHENE = {
    'SCHEMA': 'cms.graphql.schema.schema',
}


# Wagtail config, used in cms
# TODO: configure wagtail search backend, probably simple DB-search
# for development to avoid dependencies and a more advanced search
# backend for production.
WAGTAIL_SITE_NAME = "Datateknologsektionen"
WAGTAIL_ALLOW_UNICODE_SLUGS = False


# TODO: remove, these services are discontinued.
STUDENT_PORTAL_SERVICE_KEY = os.getenv('STUDENT_PORTAL_SERVICE_KEY')
KOBRA_TOKEN = os.getenv('KOBRA_TOKEN')


# TODO: maybe a bit more limited CORS.
CORS_ORIGIN_ALLOW_ALL = True

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(weeks=1),
}

LOGIN_URL = '/account/login/'

# Websocket channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "voting.sockets.channel_routing",
    },
}

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'
