"""
Django settings for dsek project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    # ---
    # Project apps
    # ---
    "account",
    "storage",
    "voting.apps.VotingConfig",
    "tools",
    "membership",
    "booking",
    "logger",
    "checkin",
    "attendance",
    "carlogging",
    "committee",
    "keylog",
    "budgetportal",
    # ---
    # Django related
    # ---
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cas",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "graphene_django",
    "imagekit",
    # ---
    # Wagtail related
    # ---
    # Wagtail project apps
    "cms.misc",
    "cms.home",
    "cms.infomail",
    "cms.infopage",
    "cms.snippets",
    "cms.post",
    # Wagtail modules
    "wagtail.contrib.styleguide",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail.core",
    "wagtail.api.v2",
    "wagtail.contrib.search_promotions",
    # "grapple",
    "modelcluster",
    "taggit",
    # auth-adfs
    "django_auth_adfs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "cas.middleware.CASMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "cas.backends.CASBackend",
    "django_auth_adfs.backend.AdfsAuthCodeBackend",
)

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "app.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Stockholm"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

# used by cms for uploads
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (os.path.join(BASE_DIR, "app", "static"),)

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

# CAS (system for LiU authentication) !!!! Being replaced !!!!
CAS_SERVER_URL = "https://login.liu.se/cas/"
CAS_LOGOUT_COMPLETELY = True
CAS_PROVIDE_URL_TO_LOGOUT = True
CAS_RESPONSE_CALLBACKS = ("account.user.cas_callback",)

### New authentication system for liu
AUTH_ADFS = {
    "SERVER": "fs.liu.se",
    "CLIENT_ID": "your-configured-client-id",
    "RELYING_PARTY_ID": "your-adfs-RPT-name",
    # Make sure to read the documentation about the AUDIENCE setting
    # when you configured the identifier as a URL!
    "AUDIENCE": "microsoft:identityserver:your-RelyingPartyTrust-identifier",
    "CA_BUNDLE": "/path/to/ca-bundle.pem",
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
}

# Configure django to redirect users to the right URL for login
LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = "/"

# User configuration sheet (for getting user info from a google docs sheet)
# TODO: this is outdated, look into this and remove.
# SA_CREDENTIALS_FILE = 'credentials.json'
# SA_FILE_ID = '1vgN5ds5LMUZ0V3lG_sHcjxCRD3NmaOTc6uVamSOxEOQ'
# SA_COL_NAME = 'Namn'
# SA_COL_LIU_ID = 'Liu-Id'
# SA_COL_UTSKOTT = 'Utskott'
# SA_COL_TITLE = 'Post utskott'

# Django REST Framework
REST_FRAMEWORK = {
    # Sets default permission requirements (403 errors) for every endpoint. Override in viewset, as shown in cms.api
    "DEFAULT_PERMISSION_CLASSES": ("app.permissions.AllowOptionsAuthentication",),
    # Sets default authentication requirements (401 errors) for every endpoint. Override in viewset, as shown in cms.api
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}

# # GraphQL configuration, right now only used in CMS.
GRAPHENE = {"SCHEMA": "cms.graphql.schema.schema"}

# GRAPHENE = {"SCHEMA": "grapple.schema.schema"}
# GRAPPLE_APPS = {
#     "misc": "",
#     "home": "",
#     "infomail": "",
#     "infopage": "",
#     "snippets": "",
#     "post": "",
# }


# Wagtail config, used in cms
# TODO: configure wagtail search backend, probably simple DB-search
# for development to avoid dependencies and a more advanced search
# backend for production.
WAGTAIL_SITE_NAME = "Datateknologsektionen"
WAGTAIL_ALLOW_UNICODE_SLUGS = False


# TODO: remove, these services are discontinued.
STUDENT_PORTAL_SERVICE_KEY = os.getenv("STUDENT_PORTAL_SERVICE_KEY")
KOBRA_TOKEN = os.getenv("KOBRA_TOKEN")


# some of these IDs can be found at: https://api.gluehome.com/api/Hubs
NETLIGHT_API_URL = "https://user-api.gluehome.com/v1"
NETLIGHT_API_KEY = os.getenv("NETLIGHT_API_KEY")
NETLIGHT_HUB_ID = os.getenv("NETLIGHT_HUB_ID")
NETLIGHT_LOCK_ID = os.getenv("NETLIGHT_LOCK_ID")
NETLIGHT_AUTHORIZATION = os.getenv("NETLIGHT_AUTHORIZATION")

GATSBY_MANAGER_URL = os.getenv("GATSBY_MANAGER_URL")

# TODO: maybe a bit more limited CORS.
CORS_ORIGIN_ALLOW_ALL = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=5),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=15),
}

LOGIN_URL = "/account/login/"

# Websocket channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "voting.sockets.channel_routing",
    }
}

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"
