"""
Django settings for dsek project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

dotenv_path = os.path.join(BASE_DIR, ".env")
load_dotenv(dotenv_path)

# Application definition

INSTALLED_APPS = [
    # ---
    # Project apps
    # ---
    "backend.account",
    "backend.voting.apps.VotingConfig",
    "backend.tools",
    "backend.locks",
    "backend.membership",
    "backend.booking",
    "backend.logger",
    "backend.checkin",
    "backend.attendance",
    "backend.carlogging",
    "backend.committee",
    "backend.keylog",
    "backend.budgetportal",
    # ---
    # Django related
    # ---
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "imagekit",
    "django_auth_adfs",
    "post_office",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #'django_auth_adfs.middleware.LoginRequiredMiddleware',
]


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "django_auth_adfs.backend.AdfsAuthCodeBackend",
    "django_auth_adfs.backend.AdfsAccessTokenBackend",
)


ROOT_URLCONF = "backend.app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    },
    {
        "BACKEND": "post_office.template.backends.post_office.PostOfficeTemplates",
        "APP_DIRS": True,
        "DIRS": [],
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.debug",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.template.context_processors.request",
            ]
        },
    },
]

WSGI_APPLICATION = "backend.app.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Stockholm"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

# used by cms for uploads
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (os.path.join(BASE_DIR, "app", "static"),)

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

CLIENT_ID = os.getenv("CLIENT_ID")
### New authentication system for liu
AUTH_ADFS = {
    # "LOGIN_EXEMPT_URLS": ["account/"],
    "SERVER": "fs.liu.se",
    "CLIENT_ID": CLIENT_ID,
    "RELYING_PARTY_ID": CLIENT_ID,
    # Make sure to read the documentation about the AUDIENCE setting
    # when you configured the identifier as a URL!
    "AUDIENCE": "microsoft:identityserver:" + str(CLIENT_ID),
    "CA_BUNDLE": True,
    "CLAIM_MAPPING": {
        "first_name": "given_name",
        "last_name": "family_name",
        "email": "email",
    },
}

# Configure django to redirect users to the right URL for login
LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = "/oauth2/callback"

# Django REST Framework
REST_FRAMEWORK = {
    # Sets default permission requirements (403 errors) for every endpoint. Override in viewset, as shown in cms.api
    "DEFAULT_PERMISSION_CLASSES": ("backend.app.permissions.AllowOptionsAuthentication",),
    # Sets default authentication requirements (401 errors) for every endpoint. Override in viewset, as shown in cms.api
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication",
    ),
}

# Home Assistant API (Locks)
BETTAN_LOCK_ID = os.getenv("BETTAN_LOCK_ID")
CONFIGURA_LOCK_ID = os.getenv("CONFIGURA_LOCK_ID")
HOME_ASSISTANT_TOKEN = os.getenv("HOME_ASSISTANT_TOKEN")
HOME_ASSISTANT_BASEURL = os.getenv("HOME_ASSISTANT_BASEURL")

GATSBY_MANAGER_URL = os.getenv("GATSBY_MANAGER_URL")

WERK_WEBHOOK_URL = os.getenv("WERK_WEBHOOK_URL", "")

# TODO: maybe a bit more limited CORS.
CORS_ORIGIN_ALLOW_ALL = True
CORS_EXPOSE_HEADERS = [*default_headers, "retry-after"]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=5),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=15),
}

# LOGIN_URL = "/account/login/"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# URL to D-sektionens calendar
CAL_URL = os.getenv(
    "CAL_URL",
    "https://calendar.google.com/calendar/ical/webmaster%40d.lintek.liu.se/public/basic.ics",
)


EMAIL_BACKEND = "post_office.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = os.environ.get("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@d-sektionen.se")
