# Generated by Django 4.2.14 on 2025-03-03 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='attendant_limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='For no limit the value should be 0.'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='attendants',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
