# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20190227_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='entry',
            name='severity',
            field=models.CharField(choices=[('F', 'Fatal'), ('E', 'Error'), ('W', 'Warning'), ('I', 'Info'), ('D', 'Debug')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
