# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20190228_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('NL', 'Netlight'), ('UN', 'Uncategorized')], default='UN', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
