# Generated by Django 2.2.17 on 2021-05-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carlogging', '0003_logentry_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='end_car_cleaned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='end_message',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_car_cleaned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_message',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LogStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_km', models.IntegerField(null=True)),
                ('start_message', models.TextField(blank=True, max_length=200)),
                ('start_car_cleaned', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
