# Generated by Django 2.2.17 on 2021-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0004_auto_20210501_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logstart',
            name='user',
        ),
        migrations.AddField(
            model_name='logentry',
            name='liu_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='logstart',
            name='liu_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
