# Generated by Django 2.2.17 on 2021-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0006_auto_20210501_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='liu_id',
            new_name='booking_liu_id',
        ),
        migrations.RemoveField(
            model_name='logstart',
            name='liu_id',
        ),
        migrations.AddField(
            model_name='logstart',
            name='booking_liu_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='end_car_cleaned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='end_km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logstart',
            name='start_km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logstart',
            name='start_message',
            field=models.TextField(max_length=200),
        ),
    ]
