# Generated by Django 2.2.17 on 2021-05-04 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0007_auto_20210501_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='start_car_cleaned',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='start_km',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='start_message',
        ),
        migrations.AddField(
            model_name='logentry',
            name='log_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carlogging.LogStart'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='logging_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logstart',
            name='logging_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logstart',
            name='logging_finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
