# Generated by Django 2.2.17 on 2021-05-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0008_auto_20210504_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='user',
            new_name='logging_user',
        ),
        migrations.RenameField(
            model_name='logstart',
            old_name='user',
            new_name='logging_user',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='log_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carlogging.LogStart'),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='logging_finished',
            field=models.BooleanField(null=True),
        ),
    ]
