# Generated by Django 2.2.17 on 2021-05-08 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carlogging', '0009_auto_20210504_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='booking_liu_id',
        ),
        migrations.RemoveField(
            model_name='logstart',
            name='booking_liu_id',
        ),
        migrations.AddField(
            model_name='logentry',
            name='booking_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logstart',
            name='booking_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='logging_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_logging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='logging_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_logging', to=settings.AUTH_USER_MODEL),
        ),
    ]
