# Generated by Django 2.2.17 on 2021-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0010_auto_20210508_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
