# Generated by Django 2.2.17 on 2021-11-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0011_logentry_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='active_member',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='member',
        ),
    ]
