# Generated by Django 2.2.17 on 2021-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0012_auto_20211125_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='end_car_cleaned',
            new_name='car_cleaned',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='end_km',
            new_name='kilometers',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='end_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='logstart',
            old_name='start_car_cleaned',
            new_name='car_cleaned',
        ),
        migrations.RenameField(
            model_name='logstart',
            old_name='start_km',
            new_name='kilometers',
        ),
        migrations.RemoveField(
            model_name='logstart',
            name='start_message',
        ),
        migrations.AddField(
            model_name='logstart',
            name='message',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='car_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='trailer_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='logging_finished',
            field=models.BooleanField(default=False),
        ),
    ]
