# Generated by Django 2.2.17 on 2021-12-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201127_1610'),
        ('carlogging', '0013_auto_20211126_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstart',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_booking', to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='booking_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='logging_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_logging_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
