# Generated by Django 2.2.17 on 2021-12-02 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201127_1610'),
        ('carlogging', '0014_auto_20211202_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstart',
            name='booking',
        ),
        migrations.AddField(
            model_name='logentry',
            name='trailer_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_trailer_booking', to='booking.Booking'),
        ),
        migrations.AddField(
            model_name='logstart',
            name='car_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_car_booking', to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='booking_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='logging_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_logging_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
