# Generated by Django 2.2.17 on 2021-12-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0015_auto_20211202_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='trailer',
        ),
    ]
