# Generated by Django 2.2.17 on 2021-12-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0016_remove_logentry_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='trailer_booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_trailer_booking', to='booking.Booking'),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='car_booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_car_booking', to='booking.Booking'),
        ),
    ]
