# Generated by Django 2.2.17 on 2021-12-09 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carlogging', '0017_auto_20211207_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='trailer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_trailer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
