# Generated by Django 2.2.17 on 2022-02-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_committee_contact'),
        ('carlogging', '0018_logentry_trailer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='committee.Committee'),
        ),
    ]
