# Generated by Django 2.2.17 on 2022-02-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0019_logentry_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_start',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entry', to='carlogging.LogStart'),
        ),
    ]
