# Generated by Django 2.2.17 on 2022-02-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0020_auto_20220203_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logstart',
            name='logging_finished',
        ),
    ]
