# Generated by Django 2.2.17 on 2022-02-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carlogging', '0021_remove_logstart_logging_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='booking_user',
            new_name='car_user',
        ),
        migrations.RenameField(
            model_name='logstart',
            old_name='booking_user',
            new_name='car_user',
        ),
    ]
