# Generated by Django 2.2.17 on 2022-02-06 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlogging', '0022_auto_20220206_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='car_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_entries_car_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logstart',
            name='car_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlogging_starts_car_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
