# Generated by Django 2.2.17 on 2021-11-18 18:20

import budgetportal.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(max_length=512)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(validators=[budgetportal.validators.validate_datetime_future])),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('clearing', models.TextField()),
                ('banknr', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('approvedKas', models.BooleanField(blank=True, default=False)),
                ('approvedDeg', models.BooleanField(blank=True, default=False)),
                ('payed', models.BooleanField(blank=True, default=False)),
                ('ipaddr', models.GenericIPAddressField()),
                ('total_sum', models.FloatField(default=0)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
