# Generated by Django 2.2.17 on 2021-11-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Article'),
        ),
    ]
