# Generated by Django 2.2.17 on 2022-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0010_budgetentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipt'),
        ),
    ]
