# Generated by Django 2.2.17 on 2022-01-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0013_budgetentry_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetentry',
            old_name='document',
            new_name='report_pdf',
        ),
    ]
