# Generated by Django 2.2.17 on 2022-02-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0018_file'),
        ('committee', '0004_auto_20220224_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.Committee'),
        ),
    ]
