# Generated by Django 2.2.17 on 2022-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0019_auto_20220203_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='list_test',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
