# Generated by Django 2.2.17 on 2022-02-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0020_budgetentry_list_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='list_test',
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='list_test',
            field=models.ManyToManyField(blank=True, related_name='files', to='budgetportal.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipt/%Y/%m/%d/'),
        ),
    ]
