# Generated by Django 2.2.17 on 2022-02-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0022_remove_budgetentry_list_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.BudgetEntry'),
        ),
    ]
