# Generated by Django 2.2.17 on 2022-02-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0025_auto_20220218_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='total_sum',
        ),
    ]
