# Generated by Django 2.2.17 on 2022-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0027_auto_20220303_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='denied',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
