# Generated by Django 2.2.17 on 2021-11-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0005_auto_20211118_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='articles',
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='articles',
            field=models.ManyToManyField(blank=True, to='budgetportal.Article'),
        ),
    ]
