# Generated by Django 2.2.17 on 2021-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0006_auto_20211118_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='articles',
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='articles',
            field=models.TextField(null=True),
        ),
    ]
