# Generated by Django 2.2.17 on 2021-11-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0007_auto_20211118_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='articles',
            field=models.TextField(blank=True),
        ),
    ]
