# Generated by Django 2.2.17 on 2021-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0009_auto_20211125_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exspense_receipt'),
        ),
    ]
