# Generated by Django 2.2.17 on 2022-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0012_auto_20220120_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
