# Generated by Django 2.2.17 on 2022-01-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0014_auto_20220127_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipt/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='expense_receipt/%Y/%m/%d/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='budgetportal.ImageAlbum')),
            ],
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='budgetportal.ImageAlbum'),
        ),
    ]
