# Generated by Django 2.2.17 on 2022-01-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0015_auto_20220127_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='image2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Image'),
        ),
    ]
