# Generated by Django 2.2.17 on 2022-05-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0028_budgetentry_denied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetentry',
            options={'ordering': ('date',)},
        ),
    ]
