# Generated by Django 2.2.17 on 2022-04-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committee', '0004_auto_20220224_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='contact',
        ),
        migrations.AddField(
            model_name='committee',
            name='treasurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='treasurer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
