# Generated by Django 4.2.14 on 2024-12-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0010_auto_20230925_1909'),
        ('committee', '0006_auto_20221103_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='chair_email',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='members',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='treasurer',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='treasurer_email',
        ),
        migrations.AddField(
            model_name='committee',
            name='chairman_permissions',
            field=models.ManyToManyField(related_name='chairman_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='committee',
            name='other_permissions',
            field=models.ManyToManyField(related_name='other_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='committee',
            name='treasurer_permissions',
            field=models.ManyToManyField(related_name='treasurer_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('role_name', models.CharField(max_length=255)),
                ('role_type', models.CharField(choices=[('tr', 'treasurer'), ('ch', 'chair'), ('ot', 'other')], default='ot', max_length=2)),
                ('year', models.CharField(max_length=5)),
                ('has_permissions_until', models.DateField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committee')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
