# Generated by Django 4.2.14 on 2025-11-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_item_requires_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('service', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack')], default='slack', max_length=7)),
                ('url', models.CharField(default=None, max_length=2048, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.webhook'),
        ),
    ]
