# Generated by Django 4.2.14 on 2025-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_item_requires_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
