# Generated by Django 4.2.14 on 2025-11-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_item_requires_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_booking_hours',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='item',
            name='max_booking_hours_restricted_timeslot',
            field=models.IntegerField(default=720),
        ),
    ]
