# Generated by Django 4.2.14 on 2025-11-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_item_max_booking_hours_and_more'),
        ('booking', '0015_webhook_item_webhook'),
    ]

    operations = [
    ]
