# Generated by Django 4.2.14 on 2025-11-27 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_merge_20251127_1729')
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='item',
            new_name='pool',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='booking.itemcategory'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(default=None, max_length=2048, unique=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.CreateModel(
            name='ItemPoolItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=32)),
                ('bookings', models.ManyToManyField(blank=True, related_name='items', to='booking.booking')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('bookings', models.ManyToManyField(blank=True, related_name='accessories', to='booking.booking')),
                ('compatible_items', models.ManyToManyField(related_name='compatible_accessories', to='booking.itempoolitem')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='booking.item')),
            ],
        ),
    ]
