# Generated by Django 4.2.14 on 2025-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_rename_item_booking_pool_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.item'),
        ),
    ]
