# Generated by Django 4.2.14 on 2026-03-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_merge_20251127_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(default=None, max_length=2048, unique=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
