# Generated by Django 4.2.14 on 2026-02-02 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def create_items_for_pools(apps, schema_editor):
    """Create a corresponding ItemPoolItem for each existing ItemPool."""
    ItemPool = apps.get_model('booking', 'ItemPool')
    ItemPoolItem = apps.get_model('booking', 'ItemPoolItem')
    
    for pool in ItemPool.objects.all():
        # Create one item per pool with the same name
        ItemPoolItem.objects.create(
            name=pool.name,
            pool=pool,
            enabled=True,
            priority=0,
            status=None
        )


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_merge_20251127_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='item',
            new_name='pool',
        ),
        migrations.AlterField(
            model_name='booking',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='booking.itemcategory'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(default=None, max_length=2048, unique=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.CreateModel(
            name='ItemPoolItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('compatible_items', models.ManyToManyField(blank=True, related_name='compatible_accessories', to='booking.itempoolitem')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='booking.item')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.itemaccessory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(related_name='bookings', to='booking.itempoolitem'),
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemPool',
        ),
        migrations.RenameModel(
            old_name='ItemAccessory',
            new_name='ItemPoolAccessory',
        ),
        migrations.AddField(
            model_name='itempool',
            name='requires_accessory',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            create_items_for_pools,
            # items get automatically deleted on reverse due to their table being dropped
            reverse_code=migrations.RunPython.noop,
        ),
    ]
