# Generated by Django 4.2.14 on 2026-03-02 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_item_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='accessories',
            field=models.ManyToManyField(related_name='bookings', to='booking.itempoolaccessory'),
        ),
    ]
