# Generated by Django 4.2.14 on 2025-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_booking_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaccessory',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='itempoolitem',
            name='bookings',
        ),
        migrations.AddField(
            model_name='booking',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.itemaccessory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(related_name='bookings', to='booking.itempoolitem'),
        ),
    ]
