# Generated by Django 4.2.14 on 2025-11-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_itemaccessory_bookings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemPool',
        ),
        migrations.RenameModel(
            old_name='ItemAccessory',
            new_name='ItemPoolAccessory',
        ),
    ]
