# Generated by Django 4.2.14 on 2026-03-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_webhook_url'),
        ('booking', '0018_booking_count_alter_booking_accessories'),
    ]

    operations = [
    ]
