# Generated by Django 4.2.14 on 2025-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_rename_item_itempool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempool',
            name='requires_accessory',
            field=models.BooleanField(default=False),
        ),
    ]
