# Generated by Django 4.2.14 on 2026-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_merge_20260312_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.itempoolaccessory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.itempoolitem'),
        ),
    ]
