# Generated by Django 4.2.14 on 2026-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_booking_accessories_alter_booking_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempool',
            name='max_booking_hours',
        ),
        migrations.RemoveField(
            model_name='itempool',
            name='max_booking_hours_restricted_timeslot',
        ),
        migrations.RenameField(
            model_name='itempool',
            old_name='requires_confirmation',
            new_name='always_requires_confirmation',
        ),
        migrations.AddField(
            model_name='itempool',
            name='auto_confirm_max_booking_hours',
            field=models.FloatField(default=72),
        ),
        migrations.AddField(
            model_name='itempool',
            name='min_booking_hours',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='itempool',
            name='min_booking_hours_restricted_timeslot',
            field=models.FloatField(default=1),
        ),
    ]
