# Generated by Django 4.2.14 on 2025-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_itempool_requires_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempoolaccessory',
            name='compatible_items',
            field=models.ManyToManyField(blank=True, related_name='compatible_accessories', to='booking.itempoolitem'),
        ),
    ]
