# Generated by Django 4.2.14 on 2026-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_itempoolaccessory_compatible_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempoolitem',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
