# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-22 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doorkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='doorkeeper',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Event'),
        ),
        migrations.AddField(
            model_name='doorkeeper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doorkeeper',
            unique_together=set([('user', 'event')]),
        ),
    ]
