# Generated by Django 2.2.2 on 2019-12-10 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clear_data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
