# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 26, 15, 2, 57, 81073)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='belongs_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Object'),
        ),
    ]
