# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='until_further_notice',
        ),
    ]
