# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_testing_until_further_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
