# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_delete_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Object'),
        ),
    ]
