# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_storageroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageroom',
            name='model_url',
            field=models.TextField(default=''),
        ),
    ]
