# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_storageroom_model_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storageroom',
            name='model_url',
            field=models.TextField(blank=True),
        ),
    ]
