# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20180326_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='in_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
