# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-15 14:33
from __future__ import unicode_literals

import cms.snippets.validators
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20181226_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=6, validators=[functools.partial(cms.snippets.validators.color_lightness_checker, *(248,), **{})])),
                ('panel_color', models.CharField(max_length=6, validators=[functools.partial(cms.snippets.validators.color_lightness_checker, *(240,), **{})])),
            ],
        ),
    ]
