# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-27 21:05
from __future__ import unicode_literals

import cms.snippets.validators
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(max_length=6, validators=[functools.partial(cms.snippets.validators.color_lightness_checker, *(242,), **{})]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='panel_color',
            field=models.CharField(max_length=6, validators=[functools.partial(cms.snippets.validators.color_lightness_checker, *(230,), **{})]),
        ),
    ]
