# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-24 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.Event')),
                ('members_only', models.BooleanField(default=False)),
                ('clear_data', models.DateField()),
                ('attendant_limit', models.IntegerField()),
                ('attendants', models.ManyToManyField(related_name='_occurrence_attendants_+', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('checkin.event',),
        ),
    ]
