# Generated by Django 2.2.2 on 2019-07-07 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='attendants',
            field=models.ManyToManyField(blank=True, related_name='_occurrence_attendants_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
