# Generated by Django 2.2.2 on 2019-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190707_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='attendant_limit',
            field=models.IntegerField(default=0),
        ),
    ]
