# Generated by Django 2.2.2 on 2019-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190712_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='blacklist',
            field=models.TextField(blank=True, help_text='Separate using space, line-break or comma.'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='whitelist',
            field=models.TextField(blank=True, help_text='Separate using space, line-break or comma. Leave empty for no whitelist.'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='attendant_limit',
            field=models.IntegerField(default=0, help_text='For no limit the value should be 0.'),
        ),
    ]
