# Generated by Django 2.2.2 on 2019-12-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190928_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='clear_data',
        ),
    ]
