name: Publish Docker image

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.d-sektionen.se
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.d-sektionen.se/backend
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}    # 'latest' for default branch only
            type=ref,event=branch                                  # branch name tag (master, development)
            type=sha,format=short                                  # commit SHA tag

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
