name: Test backend

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: python src/manage.py test voting
